"""Paths and tunable parameters. All paths are relative to the project root."""

from __future__ import annotations

from pathlib import Path

APP_ROOT = Path(__file__).resolve().parents[1]
MODELS_DIR = APP_ROOT / "models"
LOGS_DIR = APP_ROOT / "logs"
SCREENSHOTS_DIR = APP_ROOT / "screenshots"

HOLISTIC_MODEL_NAME = "holistic_landmarker.task"
HOLISTIC_MODEL = MODELS_DIR / HOLISTIC_MODEL_NAME

MODEL_URLS: dict[str, list[str]] = {
    HOLISTIC_MODEL_NAME: [
        "https://storage.googleapis.com/mediapipe-models/holistic_landmarker/holistic_landmarker/float16/latest/holistic_landmarker.task",
        "https://storage.googleapis.com/mediapipe-models/holistic_landmarker/holistic_landmarker/float16/1/holistic_landmarker.task",
    ],
}

MIN_MODEL_BYTES = 200_000
RESOLUTIONS=[(640,480),(1280,720),(1920,1080)]
DEFAULT_RESOLUTION=(1280,720)
DEFAULT_CAMERA_INDEX=0
CAMERA_PROBE_COUNT=6
PROCESSING_SCALES=(100,75,50)
DEFAULT_PROCESSING_SCALE=75
SMOOTHING_ALPHA=0.6
LOST_FRAMES_TIMEOUT=5
SNAP_FRACTION=0.18
MIN_POSE_DETECTION_CONFIDENCE=0.5
MIN_POSE_PRESENCE_CONFIDENCE=0.5
MIN_POSE_TRACKING_CONFIDENCE=0.5
MIN_HAND_DETECTION_CONFIDENCE=0.5
MIN_HAND_PRESENCE_CONFIDENCE=0.5
MIN_HAND_TRACKING_CONFIDENCE=0.5
MIN_FACE_DETECTION_CONFIDENCE=0.5
MIN_FACE_PRESENCE_CONFIDENCE=0.5
MIN_FACE_TRACKING_CONFIDENCE=0.5
POSE_POINT_VISIBILITY=0.5
POSE_BOX_VISIBILITY=0.45
GESTURE_STABLE_FRAMES=3
MOTION_STABLE_FRAMES=3
MOTION_WINDOW_SEC=0.45
MOTION_MIN_SPAN_SEC=0.28
MOTION_HORIZ_THRESHOLD=0.03
MOTION_VERTICAL_THRESHOLD=0.035
MOTION_DEPTH_THRESHOLD=0.10
HAND_TRAIL_LENGTH=16
HAND_MOTION_WINDOW_SEC=0.40
HAND_SPEED_THRESHOLD=0.18
TARGET_CAMERA_FPS=30
